### ISSUE TITLE
Only server host unlocks chef when he is killed

### ISSUE THREAD

**Issue by Headline** [GnomeModder/ChefMod#3]
https://github.com/GnomeModder/ChefMod/blob/a492608a7e4d264226e2bfba8e135afc41d40480/thecook-vs/CHEFMod/Unlockables.cs#L30

This prevents all players from receiving the achievement, I'm not sure if you have other logic preventing this as well but my entire squad was very disappointed to see that only the server host unlocks Chef.

**Comment by Moffein** [comment]
Fixed.
