### ISSUE TITLE
Chef's pod attempts to register to network despite missing a NetworkIdentity

### ISSUE THREAD

**Issue by DestroyedClone** [GnomeModder/ChefMod#7]
On startup the following error is logged:
`[Error  : Unity Log] Could not register 'chef_fruitpod_impact' since it contains no NetworkIdentity component`

Either due to either (or both) of these two lines:
https://github.com/GnomeModder/ChefMod/blob/main/thecook-vs/CHEFMod/ChefPlugin.cs#L189
https://github.com/GnomeModder/ChefMod/blob/main/thecook-vs/CHEFMod/ChefPlugin.cs#L205

The question is, should it be registered to network or not? On one hand it works even without adding to network, on the other hand there's a SyncVar component used for syncing the index of the fruitpod's mesh and materials.

**Comment by Moffein** [comment]
Fixed as of a few updates ago.
